name: Lint

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --dev
      - name: Run gts
        run: yarn lint

      - name: Set version
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: templates/version.ts.jinja
          output_file: utils/version.ts
          strict: true
          variables: |
            version=test
      
      - name: Run gts2
        run: yarn lint
      - name: build
        run: yarn build
