# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set version
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: templates/version.ts.jinja
          output_file: utils/version.ts
        env:
          VERSION: "${GITHUB_REF##*/}"
          
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Update version" || echo "Nothing to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: tdu-logcation/web
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      
      
